apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raginspector.fullname" . }}-config
  namespace: {{ include "raginspector.namespace" . }}
  labels:
    {{- include "raginspector.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
